# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snipii < Formula
  desc "A CLI tool that snips PII from text using regex + validation"
  homepage "https://github.com/toritori0318/snipii"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toritori0318/snipii/releases/download/v0.7.0/snipii_darwin_amd64.tar.gz"
      sha256 "dbfdb44559b19db37a1e1e6c8ddb57d4b62c037d96962cbb46d29330f9dae58d"

      define_method(:install) do
        bin.install "snipii"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toritori0318/snipii/releases/download/v0.7.0/snipii_darwin_arm64.tar.gz"
      sha256 "4ec353ddad736b4497c5741b1f3fb73715237e2960ced853123433ae96737e97"

      define_method(:install) do
        bin.install "snipii"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toritori0318/snipii/releases/download/v0.7.0/snipii_linux_amd64.tar.gz"
      sha256 "c30d92a0834f95a2026cd8039ad7089154c3e1fadff12b8e434291007321616f"
      define_method(:install) do
        bin.install "snipii"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toritori0318/snipii/releases/download/v0.7.0/snipii_linux_arm64.tar.gz"
      sha256 "6845e32ccc8aa4e62cbb0aeade75d48d13ae869419b532d36db8cb6401a3a2b7"
      define_method(:install) do
        bin.install "snipii"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/snipii --version")
  end
end
